name: LandMines
main: me.Perdog.LandMines.LandMines
version: 0.1
commands:
    landmines:
        aliases: lm
        description: Displays help
        usage: /landmines help
    plant:
        aliases: p
        description: Plant a Landmine
        permission: Landmines.Plant
        usage: /plant
permissions:
    Landmines.*:
        description: Gives access to all commands
        default: op
        children:
            Landmines.Plant: true
    Landmines.Plant:
        description: Gives access to the plant command.
        default: true